const INCREMENT = "INCREMENT";
const DECREMENT = "DECREMENT";
const ADD = "ADD";
const UPDATE = "UPDATE"
const DELETE = "DELETE"
const SHOW = "SHOW"

export  {INCREMENT, DECREMENT, ADD, UPDATE, DELETE, SHOW}